export const symbolObjects: {
  [key: string]: {
    ar: string;
    transliteration: string;
    en?: string;
    audioURL: string;
  }[];
} = {
  'ا': [{ ar: "ا", transliteration: "", audioURL: "" }],
  " أ, إ": [
    { ar: "أ", transliteration: "", audioURL: "" },
    { ar: "إ", transliteration: "", audioURL: "" },
  ],
  آ: [{ ar: " آ", transliteration: "", audioURL: "" }],
  "ـَ, ـً": [
    { ar: "اَ", transliteration: "", audioURL: "" },
    { ar: "اً", transliteration: "", audioURL: "" },
  ],
  "ـِ, ـٍ": [
    { ar: "اِ", transliteration: "", audioURL: "" },
    { ar: "اٍ", transliteration: "", audioURL: "" },
  ],
  "ـُ, ـٌ": [{ ar: "", transliteration: "", audioURL: "" }],
  " ّ": [{ ar: "اّ", transliteration: "", audioURL: "" }],
  ب: [
    { ar: "آبٌ", transliteration: "", audioURL: "" },
    { ar: "بآٌ", transliteration: "", audioURL: "" },
    { ar: "آٌ بآٌ", transliteration: "", audioURL: "" },
    { ar: "بَبُّبْ", transliteration: "", audioURL: "" },
    { ar: "بِبْبِبَ", transliteration: "", audioURL: "" },
    { ar: "بُبْبُبِّ", transliteration: "", audioURL: "" },
    { ar: "بَبْبَبَّ", transliteration: "", audioURL: "" },
    { ar: "بِبَّبْبِ", transliteration: "", audioURL: "" },
  ],
  ت: [
    { ar: "تُبَبَّة", transliteration: "", en: "a small berry", audioURL: "" },
    {
      ar: "تَبَّتْ",
      transliteration: "",
      en: "destroyed or perished",
      audioURL: "",
    },
    { ar: "تِبَبْتَبَ", transliteration: "", audioURL: "" },
    { ar: "تُبِبِّتْ", transliteration: "", audioURL: "" },
    { ar: "تَبَّتِ", transliteration: "", en: "she perished", audioURL: "" },
    { ar: "تَتَّبِبْ", transliteration: "", audioURL: "" },
    { ar: "تُبِّبْتَ", transliteration: "", audioURL: "" },
    { ar: "تِبَبَتَّ", transliteration: "", audioURL: "" },
    { ar: "تُبْبَتِّ", transliteration: "", audioURL: "" },
    { ar: "تَبِّتِ", transliteration: "", audioURL: "" },
  ],
  ث: [
    { ar: "ثُمَّة", transliteration: "", en: "there is/are", audioURL: "" },
    { ar: "ثَمَّة", transliteration: "", en: "there is/are", audioURL: "" },
    { ar: "ثِبَبْثَبَ", transliteration: "", audioURL: "" },
    { ar: "ثُبِبِّثْ", transliteration: "", audioURL: "" },
    { ar: "ثَبَّثِ", transliteration: "", en: "he stuttered", audioURL: "" },
    { ar: "ثَتَّبِبْ", transliteration: "", audioURL: "" },
    { ar: "ثُبِّبْثَ", transliteration: "", audioURL: "" },
    { ar: "ثِبَبَثَّ", transliteration: "", audioURL: "" },
    { ar: "ثُبْبَثِّ", transliteration: "", audioURL: "" },
    { ar: "ثَبِّثِ", transliteration: "", audioURL: "" },
  ],
  ج: [
    { ar: "جَبَبَّة", transliteration: "", en: "a large berry", audioURL: "" },
    {
      ar: "جُبَّتْ",
      transliteration: "",
      en: "collected or gathered",
      audioURL: "",
    },
    { ar: "جِبَبْتَبَ", transliteration: "", audioURL: "" },
    { ar: "جُبِبِّتْ", transliteration: "", audioURL: "" },
    { ar: "جَبَّتِ", transliteration: "", en: "she collected", audioURL: "" },
    { ar: "جَتَّبِبْ", transliteration: "", audioURL: "" },
    { ar: "جُبِّبْتَ", transliteration: "", audioURL: "" },
    { ar: "جِبَبَتَّ", transliteration: "", audioURL: "" },
    { ar: "جُبْبَتِّ", transliteration: "", audioURL: "" },
    { ar: "جَبِّتِ", transliteration: "", audioURL: "" },
  ],
  ح: [
    { ar: "حُبَبَّة", transliteration: "", en: "a loved one", audioURL: "" },
    { ar: "حَبَّتْ", transliteration: "", en: "loved or adored", audioURL: "" },
    { ar: "حِبَبْتَبَ", transliteration: "", audioURL: "" },
    { ar: "حُبِبِّتْ", transliteration: "", audioURL: "" },
    { ar: "حَبَّتِ", transliteration: "", en: "she loved", audioURL: "" },
    { ar: "حَتَّبِبْ", transliteration: "", audioURL: "" },
    { ar: "حُبِّبْتَ", transliteration: "", audioURL: "" },
    { ar: "حِبَبَتَّ", transliteration: "", audioURL: "" },
    { ar: "حُبْبَتِّ", transliteration: "", audioURL: "" },
    { ar: "حَبِّتِ", transliteration: "", audioURL: "" },
  ],

  خ: [
    { ar: "خُبَبَّة", transliteration: "", en: "a bite-sized", audioURL: "" },
    {
      ar: "خَبَّتْ",
      transliteration: "",
      en: "hid or concealed",
      audioURL: "",
    },
    { ar: "خِبَبْتَبَ", transliteration: "", audioURL: "" },
    { ar: "خُبِبِّتْ", transliteration: "", audioURL: "" },
    { ar: "خَبَّتِ", transliteration: "", en: "she hid", audioURL: "" },
    { ar: "خَتَّبِبْ", transliteration: "", audioURL: "" },
    { ar: "خُبِّبْتَ", transliteration: "", audioURL: "" },
    { ar: "خِبَبَتَّ", transliteration: "", audioURL: "" },
    { ar: "خُبْبَتِّ", transliteration: "", audioURL: "" },
    { ar: "خَبِّتِ", transliteration: "", audioURL: "" },
  ],
  د: [
    { ar: "دُبَبَّة", transliteration: "", en: "a teddy bear", audioURL: "" },
    {
      ar: "دَبَّتْ",
      transliteration: "",
      en: "pressed or flattened",
      audioURL: "",
    },
    { ar: "دِبَبْتَبَ", transliteration: "", audioURL: "" },
    { ar: "دُبِبِّتْ", transliteration: "", audioURL: "" },
    { ar: "دَبَّتِ", transliteration: "", en: "she pressed", audioURL: "" },
    { ar: "دَتَّبِبْ", transliteration: "", audioURL: "" },
    { ar: "دُبِّبْتَ", transliteration: "", audioURL: "" },
    { ar: "دِبَبَتَّ", transliteration: "", audioURL: "" },
    { ar: "دُبْبَتِّ", transliteration: "", audioURL: "" },
    { ar: "دَبِّتِ", transliteration: "", audioURL: "" },
  ],
  ذ: [
    { ar: "ذَكَاء", transliteration: "", en: "intelligence", audioURL: "" },
    { ar: "ذُهَب", transliteration: "", en: "gold", audioURL: "" },
    { ar: "ذِئْب", transliteration: "", en: "wolf", audioURL: "" },
    { ar: "جَذْر", transliteration: "", en: "root", audioURL: "" },
    { ar: "جَذْع", transliteration: "", en: "trunk", audioURL: "" },
    { ar: "حَذَاء", transliteration: "", en: "shoe", audioURL: "" },
    { ar: "حُجَاب", transliteration: "", en: "veil", audioURL: "" },
    { ar: "خَبَر", transliteration: "", en: "news", audioURL: "" },
    { ar: "خَزَانَة", transliteration: "", en: "wardrobe", audioURL: "" },
    { ar: "دَرْس", transliteration: "", en: "lesson", audioURL: "" },
  ],
  ر: [
    { ar: "رَأْس", transliteration: "", en: "head", audioURL: "" },
    { ar: "رَجُل", transliteration: "", en: "man", audioURL: "" },
    { ar: "رَحِم", transliteration: "", en: "womb", audioURL: "" },
    { ar: "جَرْح", transliteration: "", en: "wound", audioURL: "" },
    { ar: "جَرِيدَة", transliteration: "", en: "newspaper", audioURL: "" },
    { ar: "حَرِير", transliteration: "", en: "silk", audioURL: "" },
    { ar: "حُرَّة", transliteration: "", en: "freedom", audioURL: "" },
    { ar: "خَرِيف", transliteration: "", en: "autumn", audioURL: "" },
    { ar: "خُرُوج", transliteration: "", en: "exit", audioURL: "" },
    { ar: "دَرَّاجَة", transliteration: "", en: "bicycle", audioURL: "" },
  ],
  ز: [
    { ar: "زَمَان", transliteration: "", en: "time", audioURL: "" },
    { ar: "زَهْرَة", transliteration: "", en: "flower", audioURL: "" },
    { ar: "زَرَافَة", transliteration: "", en: "giraffe", audioURL: "" },
    { ar: "جَزَر", transliteration: "", en: "carrot", audioURL: "" },
    { ar: "جَزِيرَة", transliteration: "", en: "island", audioURL: "" },
    { ar: "حَزَام", transliteration: "", en: "belt", audioURL: "" },
    { ar: "حُزْمَة", transliteration: "", en: "bundle", audioURL: "" },
    { ar: "خَزَان", transliteration: "", en: "tank", audioURL: "" },
    { ar: "خُزَامَى", transliteration: "", en: "lavender", audioURL: "" },
    { ar: "دَزَنَة", transliteration: "", en: "basket", audioURL: "" },
  ],
  س: [
    { ar: "سَمَاء", transliteration: "", en: "sky", audioURL: "" },
    { ar: "سَفِينَة", transliteration: "", en: "ship", audioURL: "" },
    { ar: "سَاعَة", transliteration: "", en: "clock", audioURL: "" },
    { ar: "جَسَم", transliteration: "", en: "body", audioURL: "" },
    { ar: "جَسِيم", transliteration: "", en: "particle", audioURL: "" },
    { ar: "حَسَاب", transliteration: "", en: "account", audioURL: "" },
    { ar: "حُسْن", transliteration: "", en: "beauty", audioURL: "" },
    { ar: "خَسَارَة", transliteration: "", en: "loss", audioURL: "" },
    { ar: "خَسِر", transliteration: "", en: "lose", audioURL: "" },
    { ar: "دَسَاتِين", transliteration: "", en: "dresses", audioURL: "" },
  ],
  ش: [
    { ar: "شَمْس", transliteration: "", en: "sun", audioURL: "" },
    { ar: "شَجَرَة", transliteration: "", en: "tree", audioURL: "" },
    { ar: "شَهْر", transliteration: "", en: "month", audioURL: "" },
    { ar: "جَشَع", transliteration: "", en: "greedy", audioURL: "" },
    { ar: "جَشَم", transliteration: "", en: "big nose", audioURL: "" },
    { ar: "حَشَرَة", transliteration: "", en: "insect", audioURL: "" },
    { ar: "حَشِيش", transliteration: "", en: "cannabis", audioURL: "" },
    { ar: "خَشَب", transliteration: "", en: "wood", audioURL: "" },
    { ar: "خَشِن", transliteration: "", en: "rough", audioURL: "" },
    { ar: "دَشَّنَا", transliteration: "", en: "we showered", audioURL: "" },
  ],
  ص: [
    { ar: "صَلاة", transliteration: "", en: "prayer", audioURL: "" },
    { ar: "صَحْن", transliteration: "", en: "plate", audioURL: "" },
    { ar: "صَوْت", transliteration: "", en: "sound", audioURL: "" },
    { ar: "جَصَاصَة", transliteration: "", en: "scissors", audioURL: "" },
    { ar: "جَصَم", transliteration: "", en: "thick", audioURL: "" },
    { ar: "حَصَان", transliteration: "", en: "horse", audioURL: "" },
    { ar: "حَصِيرَة", transliteration: "", en: "mat", audioURL: "" },
    { ar: "خَصْلَة", transliteration: "", en: "trait", audioURL: "" },
    { ar: "خَصِيصَة", transliteration: "", en: "specialty", audioURL: "" },
    { ar: "دَصَاصَة", transliteration: "", en: "clip", audioURL: "" },
  ],
  ض: [
    { ar: "ضَوْء", transliteration: "", en: "light", audioURL: "" },
    { ar: "ضَبْط", transliteration: "", en: "control", audioURL: "" },
    { ar: "ضَحِك", transliteration: "", en: "laugh", audioURL: "" },
    { ar: "جَضَل", transliteration: "", en: "confuse", audioURL: "" },
    { ar: "جَضَم", transliteration: "", en: "molar tooth", audioURL: "" },
    { ar: "حَضَانَة", transliteration: "", en: "nursery", audioURL: "" },
    { ar: "حَضِيرَة", transliteration: "", en: "shed", audioURL: "" },
    { ar: "خَضْرَاء", transliteration: "", en: "green", audioURL: "" },
    { ar: "خَضِيرَة", transliteration: "", en: "vegetable", audioURL: "" },
    { ar: "دَضَاضَة", transliteration: "", en: "teether", audioURL: "" },
  ],
  ط: [
    { ar: "طَاقَة", transliteration: "", en: "energy", audioURL: "" },
    { ar: "طَبِيعَة", transliteration: "", en: "nature", audioURL: "" },
    { ar: "طَلَب", transliteration: "", en: "request", audioURL: "" },
    { ar: "جَطَح", transliteration: "", en: "trample", audioURL: "" },
    { ar: "جَطَم", transliteration: "", en: "thick-necked", audioURL: "" },
    { ar: "حَطَب", transliteration: "", en: "firewood", audioURL: "" },
    { ar: "حَطِيئَة", transliteration: "", en: "hasty", audioURL: "" },
    { ar: "خَطَأ", transliteration: "", en: "mistake", audioURL: "" },
    { ar: "خَطِير", transliteration: "", en: "dangerous", audioURL: "" },
    { ar: "دَطَاطِيّ", transliteration: "", en: "squishy", audioURL: "" },
  ],
  ظ: [
    { ar: "ظَلِيل", transliteration: "", en: "shadowy", audioURL: "" },
    { ar: "ظَفِر", transliteration: "", en: "nail", audioURL: "" },
    { ar: "ظَهِيرَة", transliteration: "", en: "afternoon", audioURL: "" },
    { ar: "ظَرِيف", transliteration: "", en: "funny", audioURL: "" },
    { ar: "جَظِيم", transliteration: "", en: "great", audioURL: "" },
    { ar: "حَظَّة", transliteration: "", en: "moment", audioURL: "" },
    { ar: "حَظِيرَة", transliteration: "", en: "shed", audioURL: "" },
    { ar: "خَظَم", transliteration: "", en: "dome", audioURL: "" },
    { ar: "حَظّ", transliteration: "", en: "luck", audioURL: "" },
    { ar: "دَظَر", transliteration: "", en: "patience", audioURL: "" },
  ],
  ع: [
    { ar: "عَيْن", transliteration: "", en: "eye", audioURL: "" },
    { ar: "عُمْر", transliteration: "", en: "age", audioURL: "" },
    { ar: "عَقْل", transliteration: "", en: "mind", audioURL: "" },
    { ar: "جَعَل", transliteration: "", en: "make", audioURL: "" },
    { ar: "جَمْعَة", transliteration: "", en: "Friday", audioURL: "" },
    { ar: "حَقْل", transliteration: "", en: "field", audioURL: "" },
    { ar: "حَصَاة", transliteration: "", en: "pebble", audioURL: "" },
    { ar: "خَبِيئَة", transliteration: "", en: "hideout", audioURL: "" },
    { ar: "خُزَامَى", transliteration: "", en: "lavender", audioURL: "" },
    { ar: "دَعْبَة", transliteration: "", en: "playfulness", audioURL: "" },
  ],
  غ: [
    { ar: "غَيْم", transliteration: "", en: "cloud", audioURL: "" },
    { ar: "غُرْبَة", transliteration: "", en: "loneliness", audioURL: "" },
    { ar: "غَدَاء", transliteration: "", en: "lunch", audioURL: "" },
    { ar: "جَغَرَفِيَا", transliteration: "", en: "geography", audioURL: "" },
    { ar: "جَغَل", transliteration: "", en: "foolish", audioURL: "" },
    { ar: "حَغْل", transliteration: "", en: "burden", audioURL: "" },
    { ar: "حَرَاغ", transliteration: "", en: "idle", audioURL: "" },
    { ar: "خَغَايَة", transliteration: "", en: "extreme", audioURL: "" },
    { ar: "خُغْتَة", transliteration: "", en: "deception", audioURL: "" },
    { ar: "دَغَشْ", transliteration: "", en: "dirty", audioURL: "" },
  ],
  ف: [
    { ar: "فَرَح", transliteration: "", en: "joy", audioURL: "" },
    { ar: "فَكَرَة", transliteration: "", en: "idea", audioURL: "" },
    { ar: "فُصُول", transliteration: "", en: "seasons", audioURL: "" },
    { ar: "جَفَاف", transliteration: "", en: "drought", audioURL: "" },
    { ar: "جَفَل", transliteration: "", en: "cross-eyed", audioURL: "" },
    { ar: "حَفَلَة", transliteration: "", en: "celebration", audioURL: "" },
    { ar: "حَفْرَة", transliteration: "", en: "hole", audioURL: "" },
    { ar: "خَفَاش", transliteration: "", en: "bat", audioURL: "" },
    { ar: "خِفَافِيَة", transliteration: "", en: "lightweight", audioURL: "" },
    { ar: "دَفَء", transliteration: "", en: "warmth", audioURL: "" },
  ],
  ق: [
    { ar: "قَمَر", transliteration: "", en: "moon", audioURL: "" },
    { ar: "قَلَم", transliteration: "", en: "pen", audioURL: "" },
    { ar: "قُرْص", transliteration: "", en: "tablet", audioURL: "" },
    { ar: "جَقَدَة", transliteration: "", en: "necklace", audioURL: "" },
    { ar: "جَقَف", transliteration: "", en: "stumble", audioURL: "" },
    { ar: "حَقِيقَة", transliteration: "", en: "truth", audioURL: "" },
    { ar: "حَقْل", transliteration: "", en: "field", audioURL: "" },
    { ar: "حَقَبَة", transliteration: "", en: "era", audioURL: "" },
    { ar: "خَطَأ", transliteration: "", en: "mistake", audioURL: "" },
    { ar: "دَقَة", transliteration: "", en: "precision", audioURL: "" },
  ],

  ك: [
    { ar: "كَتَاب", transliteration: "", en: "book", audioURL: "" },
    { ar: "كَلِمَة", transliteration: "", en: "word", audioURL: "" },
    { ar: "كُرْسِي", transliteration: "", en: "chair", audioURL: "" },
    { ar: "كَرِيم", transliteration: "", en: "generous", audioURL: "" },
    { ar: "حَكَى", transliteration: "", en: "narrated", audioURL: "" },
    { ar: "حَكْمَة", transliteration: "", en: "wisdom", audioURL: "" },
    { ar: "حَكِيم", transliteration: "", en: "wise", audioURL: "" },
    { ar: "خَبْز", transliteration: "", en: "bread", audioURL: "" },
    { ar: "خَبِيث", transliteration: "", en: "evil", audioURL: "" },
    { ar: "دَكَّة", transliteration: "", en: "bench", audioURL: "" },
  ],

  ل: [
    { ar: "لَوْن", transliteration: "", en: "color", audioURL: "" },
    { ar: "لِسَان", transliteration: "", en: "tongue", audioURL: "" },
    { ar: "لَوْحَة", transliteration: "", en: "board", audioURL: "" },
    { ar: "جَلَد", transliteration: "", en: "skin", audioURL: "" },
    { ar: "جَلَبَة", transliteration: "", en: "commotion", audioURL: "" },
    { ar: "حَلَاق", transliteration: "", en: "barber", audioURL: "" },
    { ar: "حَلْم", transliteration: "", en: "dream", audioURL: "" },
    { ar: "خَلَاصَة", transliteration: "", en: "summary", audioURL: "" },
    { ar: "دَلِيل", transliteration: "", en: "guide", audioURL: "" },
    { ar: "لَيْل", transliteration: "", en: "night", audioURL: "" },
  ],

  م: [
    { ar: "مَاء", transliteration: "", en: "water", audioURL: "" },
    { ar: "مَدَرَسَة", transliteration: "", en: "school", audioURL: "" },
    { ar: "مَكْتَب", transliteration: "", en: "office", audioURL: "" },
    { ar: "جَمْ", transliteration: "", en: "collect", audioURL: "" },
    { ar: "جَمَعَة", transliteration: "", en: "Friday", audioURL: "" },
    { ar: "حَمَام", transliteration: "", en: "bathroom", audioURL: "" },
    { ar: "حُمْرَة", transliteration: "", en: "redness", audioURL: "" },
    { ar: "خَمْسَة", transliteration: "", en: "five", audioURL: "" },
    { ar: "خَمَر", transliteration: "", en: "wine", audioURL: "" },
    { ar: "دَمّ", transliteration: "", en: "blood", audioURL: "" },
  ],
  ن: [
    { ar: "نَار", transliteration: "", en: "fire", audioURL: "" },
    { ar: "نَجْم", transliteration: "", en: "star", audioURL: "" },
    { ar: "نَصِيب", transliteration: "", en: "share", audioURL: "" },
    { ar: "نَصْر", transliteration: "", en: "victory", audioURL: "" },
    { ar: "جَنَاح", transliteration: "", en: "wing", audioURL: "" },
    { ar: "حَنَان", transliteration: "", en: "tenderness", audioURL: "" },
    { ar: "دَنِيء", transliteration: "", en: "lowly", audioURL: "" },
    { ar: "خَنْزِير", transliteration: "", en: "pig", audioURL: "" },
    { ar: "خَنَافِق", transliteration: "", en: "hypocrites", audioURL: "" },
    { ar: "دَنَّة", transliteration: "", en: "valley", audioURL: "" },
  ],

  ه: [
    { ar: "هَمْس", transliteration: "", en: "whisper", audioURL: "" },
    { ar: "هُدَى", transliteration: "", en: "guidance", audioURL: "" },
    { ar: "هَمَسَة", transliteration: "", en: "gesture", audioURL: "" },
    { ar: "جَهَاد", transliteration: "", en: "struggle", audioURL: "" },
    { ar: "جَهَد", transliteration: "", en: "effort", audioURL: "" },
    { ar: "حَوَاء", transliteration: "", en: "Eve", audioURL: "" },
    { ar: "حَوْض", transliteration: "", en: "basin", audioURL: "" },
    { ar: "خَوْف", transliteration: "", en: "fear", audioURL: "" },
    { ar: "خَيْط", transliteration: "", en: "thread", audioURL: "" },
    {
      ar: "دَهْمَاء",
      transliteration: "",
      en: "torrential rain",
      audioURL: "",
    },
  ],

  و: [
    { ar: "وَرْدَة", transliteration: "", en: "rose", audioURL: "" },
    { ar: "وَطَن", transliteration: "", en: "homeland", audioURL: "" },
    { ar: "وَقْت", transliteration: "", en: "time", audioURL: "" },
    { ar: "وَرَقَة", transliteration: "", en: "paper", audioURL: "" },
    { ar: "جَوَاز", transliteration: "", en: "passport", audioURL: "" },
    { ar: "حَوْل", transliteration: "", en: "around", audioURL: "" },
    { ar: "خَطَوَة", transliteration: "", en: "step", audioURL: "" },
    { ar: "خَوْف", transliteration: "", en: "fear", audioURL: "" },
    { ar: "خَطَا", transliteration: "", en: "mistake", audioURL: "" },
    { ar: "دَوْرَة", transliteration: "", en: "course", audioURL: "" },
  ],

  ى: [
    { ar: "رَؤْيَتِهَا", transliteration: "", en: "her vision", audioURL: "" },
    { ar: "سَعِدْتِي", transliteration: "", en: "my happiness", audioURL: "" },
    { ar: "شُكْرَاهِي", transliteration: "", en: "my gratitude", audioURL: "" },
    { ar: "صَدِيقِي", transliteration: "", en: "my friend", audioURL: "" },
    { ar: "ضَحِكْتِي", transliteration: "", en: "my laughter", audioURL: "" },
  ],
  ة: [
    { ar: "بَيْتَة", transliteration: "", en: "a small house", audioURL: "" },
    { ar: "تَعَلَّمْتَ", transliteration: "", en: "you learned", audioURL: "" },
    { ar: "حُبَّتِي", transliteration: "", en: "my love", audioURL: "" },
    { ar: "جَلَسْتَ", transliteration: "", en: "you sat", audioURL: "" },
    { ar: "دَرَسَتَ", transliteration: "", en: "she studied", audioURL: "" },
  ],

  ي: [
    { ar: "رَؤْيَتِي", transliteration: "", en: "my vision", audioURL: "" },
    { ar: "سَعِدْتُ", transliteration: "", en: "I was happy", audioURL: "" },
    {
      ar: "شُكْرَاكَ",
      transliteration: "",
      en: "your gratitude",
      audioURL: "",
    },
    { ar: "صَدِيقِي", transliteration: "", en: "my friend", audioURL: "" },
    { ar: "ضَحِكَتْ", transliteration: "", en: "she laughed", audioURL: "" },
  ],
};
export const arabicLetters = [
  {
    symbol: "ا",
    name: "Alef",
    description:
      'Represents the short vowel "a" sound, similar to the "a" sound in the English word "cat."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "آ",
    name: "Alef with Madda",
    description:
      'Represents a prolonged "a" sound, similar to the "a" sound in the English word "father" or the "a" sound in the word "car.',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "أ, إ",
    name: "Alef with Hamza",
    description: "Alef with Hamza",
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ـَ, ـً",
    name: "Fatha and Tanween Fatha",
    description:
      'Fatha and Tanween Fatha: Fatha represents the short "a" sound, similar to the "a" sound in the English word "cat." Tanween Fatha is a combination of Fatha and Nun, indicating a nasalized "a" sound.',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ـِ, ـٍ",
    name: "Kasra and Tanween Kasra",
    description:
      'Kasra and Tanween Kasra: Kasra represents the short "i" sound, similar to the "i" sound in the English word "sit." Tanween Kasra is a combination of Kasra and Nun, indicating a nasalized short "i" sound.',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ـُ, ـٌ",
    name: "Damma and Tanween Damma",
    description:
      'Damma and Tanween Damma: Damma represents the short "u" sound, similar to the "u" sound in the English word "put." Tanween Damma is a combination of Damma and Nun, indicating a nasalized "u" sound.',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: " ّ",
    name: "Shadda",
    description:
      "Represents the doubling or gemination of a consonant sound within a word. When a letter is marked with Shadda, it is pronounced with an emphasis or lengthening of its sound.",
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ب",
    name: "Ba",
    description: 'Represents the sound "b" as in the English word "bat."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ت",
    name: "Ta",
    description: 'Represents the sound "t" as in the English word "top."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ث",
    name: "Tha",
    description: 'Represents the sound "th" as in the English word "think."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ج",
    name: "Jim",
    description: 'Represents the sound "j" as in the English word "jam."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ح",
    name: "Ha",
    description: 'Represents the sound "h" as in the English word "hot."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "خ",
    name: "Kha",
    description:
      'Represents a guttural "kh" sound, similar to the "ch" sound in the Scottish word "loch."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "د",
    name: "Dal",
    description: 'Represents the sound "d" as in the English word "dog."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ذ",
    name: "Thal",
    description: 'Represents the sound "th" as in the English word "that."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ر",
    name: "Ra",
    description: 'Represents the sound "r" as in the English word "red."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ز",
    name: "Zain",
    description: 'Represents the sound "z" as in the English word "zero."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "س",
    name: "Seen",
    description: 'Represents the sound "s" as in the English word "sun."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ش",
    name: "Sheen",
    description:
      'Sheen: Represents the sound "sh" as in the English word "sheep."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ص",
    name: "Sad",
    description:
      'Represents the sound "s" but pronounced with the tongue pressed against the upper gum ridge, similar to the "s" sound in the English word "sun."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ض",
    name: "Dad",
    description:
      'Represents the sound "d" but pronounced with the tongue pressed against the upper gum ridge, similar to the "d" sound in the English word "dog."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ط",
    name: "Ta with Slight Emphasis",
    description:
      'Represents the sound "t" but pronounced with a slight emphasis, similar to the "t" sound in the English word "top."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ظ",
    name: "Za with Slight Emphasis",
    description:
      'Represents the sound "z" but pronounced with a slight emphasis, similar to the "z" sound in the English word "zero."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ع",
    name: "Ain",
    description:
      'Represents a guttural sound made deep in the throat, similar to the sound of a "g" followed by a "h," but without fully pronouncing either. No equivalent sound in English.',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "غ",
    name: "Ghain",
    description:
      'Represents a guttural sound made deep in the throat, similar to the "r" sound in the French word "rue." No equivalent sound in English.',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ف",
    name: "Fa",
    description: 'Represents the sound "f" as in the English word "fun."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ق",
    name: "Qaf",
    description:
      'Represents a guttural "k" sound, similar to the "k" sound in the English word "key."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ك",
    name: "Kaf",
    description: 'Represents the sound "k" as in the English word "key."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ل",
    name: "Lam",
    description: 'Represents the sound "l" as in the English word "love."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "م",
    name: "Meem",
    description: 'Represents the sound "m" as in the English word "moon."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ن",
    name: "Noon",
    description: 'Represents the sound "n" as in the English word "nice."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ه",
    name: "Ha",
    description: 'Represents the sound "h" as in the English word "hot."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ة",
    name: "Ta Marbuta",
    description:
      'Represents the sound "h" as in the English word "hot." It is a feminine marker and not pronounced in isolation.',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "و",
    name: "Waw",
    description: 'Represents the sound "w" as in the English word "water."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ى",
    name: "Alef Maqsurah",
    description:
      'Represents the short vowel "a" sound, similar to the "a" sound in the English word "cat." It appears only at the end of words and functions as a long "a."',
    audioURL: undefined,
    transliteration: "",
  },
  {
    symbol: "ي",
    name: "Ya",
    description: 'Represents the sound "y" as in the English word "yes."',
    audioURL: undefined,
    transliteration: "",
  },
] as const;
