import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Zeriphus</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex min-h-screen flex-col ">
        <div className=" ml-[6vw] mt-[15vh] flex h-auto w-auto max-w-3xl flex-col items-center ">
          <h1 className="w-fit  text-center text-3xl text-yellow-500 lg:text-6xl ">
            Deepen your faith <br></br> through learning arabic
          </h1>
          <h2 className="mt-[22vh] h-auto text-center text-lg ">
            Zephirus is a website dedicated to teach you the writing system and
            the necessary words of a language that is at core of a faith in
            order to deepen your knowledge of your faith
            <br></br>
            Explore our options :
          </h2>
          <div className="!mt-[10vh] flex space-x-20">
            <button className="h-12 w-48 rounded-2xl bg-blue-950  transition-all duration-300 hover:text-yellow-300">
              Koine Greek
            </button>
            <button className="relative h-12 w-48 overflow-clip rounded-2xl bg-green-950 transition-all duration-300 hover:text-yellow-300 ">
              Arabic
            </button>
            <button className="h-12 w-48 rounded-2xl bg-yellow-950 transition-all duration-300 hover:text-yellow-300 ">
              Ancient Hebrew
            </button>
          </div>
        </div>

        <div className="absolute left-0 top-1/2 -translate-y-3/4">
          <svg
            width="1440"
            height="172"
            viewBox="0 0 1440 172"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M0 85.5C143.834 28.5259 507.166 -51.2378 809.825 85.5C1112.48 222.238 1363.38 142.474 1451 85.5"
              stroke="url(#paint0_linear_1_7)"
              strokeWidth="20"
            />
            <defs>
              <linearGradient
                id="paint0_linear_1_7"
                x1="725.5"
                y1="10"
                x2="725.5"
                y2="161"
                gradientUnits="userSpaceOnUse"
              >
                <stop stopColor="#CD9142" />
                <stop offset="0.973958" stopColor="#E0B777" />
              </linearGradient>
            </defs>
          </svg>
        </div>
        <div className="absolute right-0 top-1/2 -z-10 -translate-y-1/2 overflow-clip rounded-full shadow-2xl shadow-gray-300">
          <Image
            src={"/homepage/banner1.png"}
            width={512}
            height={512}
            alt={"Banner homepage for arabic"}
          />
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
